FROM python:3.13-slim

WORKDIR /app

# Install dependencies for OpenCV headless and wget
RUN apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0 wget && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p uploads outputs models

EXPOSE 5001
CMD ["python","app.py"]
